	SELECT		z.STATUS1, z.ACTUALLEAVEDATE, z.LEAVEDATE, e.EMPREF, e.FIRSTNAMES, e.SURNAME, KNOWNBY
	FROM		CE z
	INNER JOIN	TMSEMP e
	ON			e.EMPREF = z.EMPREF
	WHERE		ACTUALLEAVEDATE >= GETDATE()-60
	ORDER BY	ACTUALLEAVEDATE
	
