use mfdata
/****** Script for SelectTopNRows command from SSMS  ******/
SELECT *  FROM [mfdata].[dbo].[TMSEMP] where SURNAME = 'hAMPSHIRE'-- '0049'
SELECT *  FROM [mfdata].[dbo].[TMSEMP] where EMPREF = '0649'
SELECT TOP 10 CLKDT, DIR  FROM TMSCLK WHERE EMPREF = '0159' ORDER BY CLKDT DESC

SELECT CAST(EMPREF AS VARCHAR(4)) EMPREF, CAST(DIR AS CHAR(1)) DIR, CAST(CLKDT AS datetime) CLKDT FROM TMSCLK WHERE CLKDT > '2014-04-01 21:50:57.267' ORDER BY CLKDT 

	