use GPData
DECLARE @MinDate Datetime
DECLARE @MaxDate Datetime
DECLARE @ArchDate Datetime

SELECT @MinDate = MIN([PERIODDATE]), @MaxDate = MAX([PERIODDATE])  FROM PracticeData

IF DATEDIFF(YEAR, @MinDate, @MaxDate) > 2
BEGIN
	select @ArchDate = CAST(CAST(DATEPART(YEAR, DATEADD(YEAR, -2, @MaxDate)) AS VARCHAR) + '-01-01 00:00:00' AS datetime)
	
	INSERT INTO PracticeDataArchive(SHA, PCT, PRACTICE, BNF_CODE, BNF_NAME, ITEMS, NIC, ACTCOST, QUANTITY, PERIODDATE, PERIOD)	
	(SELECT SHA, PCT, PRACTICE, BNF_CODE, BNF_NAME, ITEMS, NIC, ACTCOST, QUANTITY, PERIODDATE, PERIOD from PracticeData
	WHERE PERIODDATE < @ArchDate)	

	delete from PracticeData WHERE PERIODDATE < @ArchDate
END

DECLARE @SQL AS VARCHAR(100)
SET @SQL= 'ALTER INDEX ALL ON ? REBUILD WITH (FILLFACTOR = 80, SORT_IN_TEMPDB = ON)'
EXEC sys.sp_MSforeachtable @command1=@SQL
GO
/*


